services:

  fastapi_app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile

    container_name: fastapi_app
    restart: unless-stopped

    ports:
      - 8797:8797
    networks:
      - backend
    volumes:
      - fastapi_app_data:/app/assets

    env_file:
      - ./env/.env.app
      - ./env/.env.postgres
      - ./env/.env.rabbitmq
      - ./env/.env.redis

    depends_on:
      pgvector:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile

    container_name: celery_worker
    restart: unless-stopped

    networks:
      - backend
    volumes:
      - fastapi_app_data:/app/assets

    env_file:
      - ./env/.env.app
      - ./env/.env.postgres
      - ./env/.env.rabbitmq
      - ./env/.env.redis

    depends_on:
      pgvector:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

    command: [ "celery", "-A", "src.worker.celery_app:celery_app", "worker", "--loglevel=info", "-Q", "process_project_data,embed_project_chunks,default" ]

  celery_beat:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile

    container_name: celery_beat
    restart: unless-stopped

    networks:
      - backend

    env_file:
      - ./env/.env.app
      - ./env/.env.postgres
      - ./env/.env.rabbitmq
      - ./env/.env.redis

    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

    command: [ "celery", "-A", "src.worker.celery_app:celery_app", "beat", "--loglevel=info" ]

  celery_flower:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile

    container_name: celery_flower
    restart: unless-stopped

    ports:
      - 5555:5555
    networks:
      - backend

    env_file:
      - ./env/.env.app
      - ./env/.env.postgres
      - ./env/.env.rabbitmq
      - ./env/.env.redis

    depends_on:
      celery_worker:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

    command: [ "celery", "-A", "src.worker.celery_app:celery_app", "flower", "--port=5555", "--conf=src/worker/flowerconfig.py" ]

  nginx:
    image: nginx:stable-alpine3.24-perl
    container_name: nginx
    restart: unless-stopped

    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - fastapi_app

  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    restart: unless-stopped

    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - pg_data:/var/lib/postgresql

    env_file:
      - ./env/.env.postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.20.1
    container_name: postgres_exporter
    restart: unless-stopped

    ports:
      - 9187:9187
    env_file:
      - ./env/.env.postgres_exporter
    networks:
      - backend

    depends_on:
      - pgvector

  qdrant:
    image: qdrant/qdrant:v1.19.1
    container_name: qdrant
    restart: unless-stopped

    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    restart: unless-stopped

    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - backend

    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles

  grafana:
    image: grafana/grafana:13.0
    container_name: grafana
    restart: unless-stopped

    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./grafana/provisioning/dashboards/json:/var/lib/grafana/dashboards:ro
    networks:
      - backend

    env_file:
      - ./env/.env.grafana

    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:v1
    container_name: node_exporter
    restart: unless-stopped

    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - backend

    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  rabbitmq:
    image: rabbitmq:4.3.5-management-alpine
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - 5672:5672 # AMQP
      - 15672:15672 # management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - backend

    env_file:
      - ./env/.env.rabbitmq

    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 60s
      timeout: 5s
      retries: 4

  redis:
    image: redis:8.8.2-trixie
    container_name: redis
    restart: unless-stopped

    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend

    env_file:
      - ./env/.env.redis

    # by default, redis doesn't read the injected env variables.
    command: >
      sh -c 'redis-server --requirepass "$$REDIS_PASSWORD" --appendonly "$$REDIS_APPENDONLY" --maxmemory "$$REDIS_MAXMEMORY" --maxmemory-policy "$$REDIS_MAXMEMORY_POLICY" --protected-mode "$$REDIS_PROTECTED_MODE"'

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  fastapi_app_data:
  pg_data:
  qdrant_data:
  prometheus_data:
  grafana_data:
  rabbitmq_data:
  redis_data:

networks:
  backend:
