services:
  pgvector:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector

    restart: always

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql

    networks:
      - backend

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  pgdata:

networks:
  backend:
