"""move the data of chunk_text column into chunk_metadata

Revision ID: 3bac44f09de2
Revises: 90fee0949881
Create Date: 2026-08-12 01:10:16.628046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bac44f09de2'
down_revision: Union[str, Sequence[str], None] = '90fee0949881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_en')
    op.drop_index(op.f('collection_ar_vector_index'), table_name='collection_ar', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_ar')
    op.alter_column('chunks', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.execute(
        """
        UPDATE chunks
        SET chunk_metadata = jsonb_set(
            COALESCE(chunk_metadata, '{}'::jsonb),
            '{text}',
            to_jsonb(chunk_text),
            true
        )
        WHERE chunk_text IS NOT NULL;
        """
    )
    op.drop_column('chunks', 'chunk_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('chunks', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_table('collection_ar',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['chunks.id'], name=op.f('collection_ar_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_ar_pkey'))
    )
    op.create_index(op.f('collection_ar_vector_index'), 'collection_ar', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('collection_en',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['chunks.id'], name=op.f('collection_en_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_en_pkey'))
    )
    op.execute(
        """
        UPDATE chunks
        SET chunk_text = chunk_metadata->>'text'
        WHERE chunk_metadata ? 'text';
        """
    )

    op.execute(
        """
        UPDATE chunks
        SET chunk_metadata = chunk_metadata - 'text'
        WHERE chunk_metadata ? 'text';
        """
    )
    # ### end Alembic commands ###
