"""removed chunk_order column

Revision ID: 922e0b023b80
Revises: 3bac44f09de2
Create Date: 2026-08-23 18:13:34.804683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922e0b023b80'
down_revision: Union[str, Sequence[str], None] = '3bac44f09de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'chunk_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_order', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
