name: Deploy Main Branch to The Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_MAIN_HOST_IP }}
          username: ahmed-hasan
          key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }}
          script: |
            set -e

            cd /home/ahmed-hasan/workspace/mini-RAG
            git fetch origin main
            git reset --hard origin/main

            sudo systemctl restart minirag.service

            echo "Waiting..."
            sleep 20

            # Turn off -e temporarily for the retry loop so grep non-zero exit doesn't abort the script
            set +e
            for i in {1..6}; do
              if ss -tuln | grep -q ':80'; then
                echo "✅ Port 80 is now active."
                break
              else
                echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
                sleep 5
              fi
            done
            set -e

            if ! ss -tuln | grep -q ':80'; then
              echo "❌ Service failed to start on port 80"
              exit 1
            fi